USE BancoDeAlimentos;

CREATE TABLE Areas(
	IDArea NVARCHAR(6) PRIMARY KEY NOT NULL,
	Area NVARCHAR(50) NULL,
	Distribucion FLOAT NULL
);

CREATE TABLE Nivel_Acceso(
	IDNivel NVARCHAR(4) PRIMARY KEY NOT NULL,
	Nivel NVARCHAR(50) NULL
);

CREATE TABLE Preguntas(
	IDPregunta INT PRIMARY KEY NOT NULL,
	Descripcion NVARCHAR(100) NOT NULL
);

CREATE TABLE Programas(
	IDPrograma NVARCHAR(6) PRIMARY KEY NOT NULL,
	Programa NVARCHAR(50) NULL
);

CREATE TABLE Proveedores(
	IDProveedor NVARCHAR(8) PRIMARY KEY NOT NULL,
	Proveedor NVARCHAR(50) NULL,
	Direccion NVARCHAR(50) NULL,
	Colonia NVARCHAR(50) NULL,
	Ciudad NVARCHAR(30) NULL,
	Estado NVARCHAR(15) NULL,
	Telefono NVARCHAR(15) NULL,
	Fax NVARCHAR(15) NULL,
	Contacto NVARCHAR(50) NULL,
	Rfc NVARCHAR(15) NULL,
	FechaAlta DATETIME NULL,
	Mail NVARCHAR(50) NULL
);

CREATE TABLE TipoDon(
	IDTipoDon NVARCHAR(8) PRIMARY KEY NOT NULL,
	TipoDon NVARCHAR(20) NOT NULL
);

CREATE TABLE Unidad(
	IDUnidad NVARCHAR(10) PRIMARY KEY NOT NULL,
	Unidad NVARCHAR(15) NULL
);

CREATE TABLE Variedad(
	IDVariedad NVARCHAR(8) PRIMARY KEY NOT NULL,
	Variedad NVARCHAR(50) NULL,
	Costo FLOAT NULL
);

CREATE TABLE Formularios(
	IDForm NVARCHAR(27) PRIMARY KEY NOT NULL,
	Descripcion NVARCHAR(50) NULL,
	Tipo SMALLINT NULL,
	Orden SMALLINT NULL
);

CREATE TABLE FoliosCarAbo(
	FolioCarAbo NCHAR(10) PRIMARY KEY NOT NULL
);

CREATE TABLE FoliosEntrada(
	FolioEntrada NCHAR(10) PRIMARY KEY NOT NULL
);

CREATE TABLE FoliosSalida(
	FolioSalida NCHAR(10) PRIMARY KEY NOT NULL
);

CREATE TABLE GrupoAlim(
	IDGrupoAlim NVARCHAR(8) PRIMARY KEY NOT NULL,
	GrupoAlim NVARCHAR(30) NULL,
	PrecioRecupera FLOAT NULL
);

CREATE TABLE GrupoInst(
	IDGrupoInst NVARCHAR(8) PRIMARY KEY NOT NULL,
	GrupoInst NVARCHAR(20) NULL
);

CREATE TABLE GrupoRef(
	IDGrupoRef NVARCHAR(10) PRIMARY KEY NOT NULL,
	GrupoRef NVARCHAR(20) NULL
);

CREATE TABLE Accesos(
	IDAccesos INT PRIMARY KEY NOT NULL,
	IDNivel NVARCHAR(4) NULL,
	IDForm NVARCHAR(27) NOT NULL,
	SubMenu BIT NOT NULL,
	Nuevo BIT NOT NULL,
	Editar BIT NOT NULL,
	Borrar BIT NOT NULL,
	Grabar BIT NOT NULL,
	Cancelar BIT NOT NULL,
	Imprimir BIT NOT NULL,
	FOREIGN KEY(IDNivel) REFERENCES Nivel_Acceso(IDNivel),
	FOREIGN KEY(IDForm) REFERENCES Formularios(IDForm)
);

CREATE TABLE AreaPrograma(
	IDAreaPrograma INT PRIMARY KEY NOT NULL,
	IDArea NVARCHAR(6) NOT NULL,
	IDPrograma NVARCHAR(6) NOT NULL,
	FOREIGN KEY(IDArea) REFERENCES Areas(IDArea),
	FOREIGN KEY(IDPrograma) REFERENCES Programas(IDPrograma)
);

CREATE TABLE Donantes(
	IDDonante NVARCHAR(8) PRIMARY KEY NOT NULL,
	Donante NVARCHAR(50) NOT NULL,
	Nombre NVARCHAR(15) NULL,
	Direccion NVARCHAR(50) NULL,
	Colonia NVARCHAR(50) NULL,
	Ciudad NVARCHAR(30) NULL,
	Estado NVARCHAR(15) NULL,
	Telefono NVARCHAR(15) NULL,
	Fax NVARCHAR(15) NULL,
	Contacto NVARCHAR(50) NULL,
	Rfc NVARCHAR(15) NULL,
	Sucursales BIT NOT NULL,
	FechaAlta DATETIME NOT NULL,
	Frecuencia NVARCHAR(1) NULL,
	Mail NVARCHAR(50) NULL,
	TipoDonante NVARCHAR(8) NULL,
	IDTipoDon NVARCHAR(8) NOT NULL,
	UsuarioAlta NVARCHAR(30) NULL,
	FOREIGN KEY(IDTipoDon) REFERENCES TipoDon(IDTipoDon)
);

CREATE TABLE Articulos(
	IDArticulo NVARCHAR(13) PRIMARY KEY NOT NULL,
	Articulo NVARCHAR(100) NULL,
	Almacen NVARCHAR(1) NULL,
	Localizacion NVARCHAR(10) NULL,
	UnidadMed1 NVARCHAR(10) NULL,
	UnidadMed2 NVARCHAR(10) NULL,
	CostoBenef1 FLOAT NULL,
	CostoBenef2 FLOAT NULL,
	CuotaRecup1 FLOAT NULL,
	CuotaRecup2 FLOAT NULL,
	Reorden1 FLOAT NULL,
	Reorden2 FLOAT NULL,
	CantidadUni FLOAT NULL,
	Peso FLOAT NULL,
	Factor FLOAT NULL,
	PMercado1 FLOAT NULL,
	PMercado2 FLOAT NULL,
	IDVariedad NVARCHAR(8) NULL,
	IDGrupoAlim NVARCHAR(8) NULL,
	IDGrupoRef NVARCHAR(10) NULL,
	IDDonante NVARCHAR(8) NULL,
	FOREIGN KEY(IDVariedad) REFERENCES Variedad(IDVariedad),
	FOREIGN KEY(IDGrupoAlim) REFERENCES GrupoAlim(IDGrupoAlim),
	FOREIGN KEY(IDGrupoRef) REFERENCES GrupoRef(IDGrupoRef),
	FOREIGN KEY(IDDonante) REFERENCES Donantes(IDDonante)
);

CREATE TABLE Existencias(
	IDExistencias INT PRIMARY KEY NOT NULL,
	IDArticulo NVARCHAR(13) NULL,
	IDArea NVARCHAR(6) NULL,
	IDPrograma NVARCHAR(6) NULL,
	FechaCad DATETIME NULL,
	Existencia FLOAT NULL,
	Asignado FLOAT NULL,
	CanPedido FLOAT NULL,
	Merma FLOAT NULL,
	Entrada FLOAT NULL,
	Salida FLOAT NULL,
	FOREIGN KEY(IDArticulo) REFERENCES Articulos(IDArticulo),
	FOREIGN KEY(IDArea) REFERENCES Areas(IDArea),
	FOREIGN KEY(IDPrograma) REFERENCES Programas(IDPrograma)
);

CREATE TABLE Movtos_Det(
	IDMovtos_Det INT PRIMARY KEY NOT NULL,
	IDFolio NVARCHAR(10) NOT NULL,
	TipoMov NVARCHAR(10) NOT NULL,
	FechaCad DATETIME NOT NULL,
	Cantidad FLOAT NOT NULL,
	Peso FLOAT NULL,
	Merma FLOAT NULL,
	CostoBenef FLOAT NULL,
	CuotaRecup FLOAT NULL,
	IDArticulo NVARCHAR(13) NULL,
	IDArea NVARCHAR(6) NULL,
	IDPrograma NVARCHAR(6) NULL,
	FOREIGN KEY(IDArticulo) REFERENCES Articulos(IDArticulo),
	FOREIGN KEY(IDArea) REFERENCES Areas(IDArea),
	FOREIGN KEY(IDPrograma) REFERENCES Programas(IDPrograma)
);

CREATE TABLE ReciboDet(
	IDRecibo_Det INT PRIMARY KEY NOT NULL,
	IDFolio NVARCHAR(10) NOT NULL,
	TipoMov NVARCHAR(10) NOT NULL,
	FechaCad DATETIME NOT NULL,
	Cantidad FLOAT NOT NULL,
	Peso FLOAT NULL,
	Merma FLOAT NULL,
	CostoBenef FLOAT NULL,
	CuotaRecup FLOAT NULL,
	IDArticulo NVARCHAR(13) NULL,
	IDArea NVARCHAR(6) NULL,
	IDPrograma NVARCHAR(6) NULL,
	FOREIGN KEY(IDArticulo) REFERENCES Articulos(IDArticulo),
	FOREIGN KEY(IDArea) REFERENCES Areas(IDArea),
	FOREIGN KEY(IDPrograma) REFERENCES Programas(IDPrograma)
);

CREATE TABLE Respuestas(
	IDRespuesta INT PRIMARY KEY NOT NULL,
	Descripcion NVARCHAR(100) NOT NULL,
	IDPregunta INT NOT NULL,
	FOREIGN KEY(IDPregunta) REFERENCES Preguntas(IDPregunta)
);


CREATE TABLE SubAreas(
	IDSubArea NVARCHAR(10) PRIMARY KEY NOT NULL,
	SubArea NVARCHAR(50) NULL,
	IDArea NVARCHAR(6) NULL,
	FOREIGN KEY(IDArea) REFERENCES Areas(IDArea)
);

CREATE TABLE Sucursales(
	IDSucursales INT PRIMARY KEY NOT NULL,
	IDSucursal NVARCHAR(50) NOT NULL,
	Direccion NVARCHAR(50) NULL,
	Colonia NVARCHAR(30) NULL,
	Ciudad NVARCHAR(20) NULL,
	Estado NVARCHAR(10) NULL,
	Telefono NVARCHAR(15) NULL,
	Fax NVARCHAR(15) NULL,
	Contacto NVARCHAR(50) NULL,
	Mail NVARCHAR(30) NULL,
	IDDonante NVARCHAR(8) NOT NULL,
	FOREIGN KEY(IDDonante) REFERENCES Donantes(IDDonante)
);

CREATE TABLE Usuarios(
	IDUsuario NVARCHAR(15) PRIMARY KEY NOT NULL,
	Nombre NVARCHAR(50) NULL,
	Contrasenia NVARCHAR(15) NULL,
	IDZona NVARCHAR(5) NULL,
	IDNivel NVARCHAR(4) NULL,
	FOREIGN KEY(IDNivel) REFERENCES Nivel_Acceso(IDNivel)
);

CREATE TABLE v_AccesoArea(
	IDArea NVARCHAR(6) NOT NULL,
	IDUsuario NVARCHAR(15) NOT NULL,
	PRIMARY KEY(IDArea, IDUsuario),
	FOREIGN KEY(IDArea) REFERENCES Areas(IDArea),
	FOREIGN KEY(IDUsuario) REFERENCES Usuarios(IDUsuario)
);

CREATE TABLE Vista_1(
	IDForm NVARCHAR(27) NOT NULL,
	IDNivel NVARCHAR(4) NOT NULL,
	Submenu BIT NOT NULL,
	Nuevo BIT NOT NULL,
	PRIMARY KEY(IDForm, IDNivel),
	FOREIGN KEY(IDForm) REFERENCES Formularios(IDForm),
	FOREIGN KEY(IDNivel) REFERENCES Nivel_Acceso(IDNivel)
);

CREATE TABLE AccesoPrograma(
	IDAccesoPrograma INT PRIMARY KEY NOT NULL,
	IDArea NVARCHAR(6) NOT NULL,
	IDPrograma NVARCHAR(6) NOT NULL,
	IDUsuario NVARCHAR(15) NOT NULL,
	FOREIGN KEY(IDArea) REFERENCES Areas(IDArea),
	FOREIGN KEY(IDPrograma) REFERENCES Programas(IDPrograma),
	FOREIGN KEY(IDUsuario) REFERENCES Usuarios(IDUsuario)
);

CREATE TABLE Instituciones(
	IDInstitucion NVARCHAR(10) PRIMARY KEY NOT NULL,
	Institucion NVARCHAR(50) NULL,
	Direccion NVARCHAR(50) NULL,
	Colonia NVARCHAR(50) NULL,
	Ciudad NVARCHAR(30) NULL,
	Estado NVARCHAR(15) NULL,
	Telefono NVARCHAR(15) NULL,
	Fax NVARCHAR(15) NULL,
	Contacto NVARCHAR(50) NULL,
	FechaAlta DATETIME NULL,
	TipoInstitucion NVARCHAR(10) NULL,
	Mail NVARCHAR(40) NULL,
	Saldo NUMERIC(18,2) NULL,
	Horario NVARCHAR(20) NULL,
	Observacion NVARCHAR(150) NULL,
	Familia NVARCHAR(10) NULL,
	Director NVARCHAR(50) NULL,
	DireccionFis NVARCHAR(50) NULL,
	ColoniaFis NVARCHAR(50) NULL,
	CiudadFis NVARCHAR(50) NULL,
	EstadoFis NVARCHAR(50) NULL,
	Rfc NVARCHAR(50) NULL,
	Personas INT NULL,
	RazonFis NVARCHAR(50) NULL,
	Activo BIT NOT NULL,
	Descuento FLOAT NULL,
	SaldoPermitido FLOAT NULL,
	DonativoPermitido FLOAT NULL,
	InstiComun NCHAR(2) NULL,
	IDGrupoInst NVARCHAR(8) NULL,
	IDSubArea NVARCHAR(10) NULL,
	FOREIGN KEY(IDGrupoInst) REFERENCES GrupoInst(IDGrupoInst),
	FOREIGN KEY(IDSubArea) REFERENCES SubAreas(IDSubArea)
);

CREATE TABLE MovCarAbo(
	IDMovCarAbo INT PRIMARY KEY NOT NULL,
	TipoMov NVARCHAR(10) NULL,
	IDFolioCarAbo NVARCHAR(10) NULL,
	IDFolio NVARCHAR(10) NULL,
	FechaMov DATETIME NULL,
	Importe NUMERIC(18,2) NULL,
	Abono NUMERIC(18,2) NULL,
	Referencia NVARCHAR(50) NULL,
	Estatus NVARCHAR(10) NULL,
	Saldo NUMERIC(18,2) NULL,
	Bonificacion NUMERIC(18,2) NULL,
	Donativo NUMERIC(18,2) NULL,
	Incobrable NUMERIC(18,2) NULL,
	IDArea NVARCHAR(6) NULL,
	IDPrograma NVARCHAR(6) NULL,
	IDInstitucion NVARCHAR(10) NULL,
	FOREIGN KEY(IDArea) REFERENCES Areas(IDArea),
	FOREIGN KEY(IDPrograma) REFERENCES Programas(IDPrograma),
	FOREIGN KEY(IDInstitucion) REFERENCES Instituciones(IDInstitucion)
);

